FROM php:8.4-apache

RUN docker-php-ext-install pdo_mysql \
    && a2enmod rewrite headers

COPY local/apache-vhost.conf /etc/apache2/sites-available/000-default.conf

RUN mkdir -p /var/www/.avereo/rapport \
    && chown -R www-data:www-data /var/www/.avereo
