import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
let cfg;
try { cfg=JSON.parse(await readFile(join(root,'.local/cockpit-local.json'),'utf8')); }
catch(error) { if(error.code!=='ENOENT')throw error;cfg=JSON.parse(await readFile(join(root,'data/cockpit-local.json'),'utf8')); }
cfg.appRoot=resolve(root,cfg.appRoot);
const {createReviewStore}=await import(pathToFileURL(resolve(cfg.appRoot,'workflows/review-store.mjs')).href);
const folder=join(root,'docs/pilotage');
const original=await readFile(join(folder,'suivi-chantier.json'));
const live=await (await createReviewStore(folder)).snapshot();
assert.deepEqual(live.data.phases.map(p=>p.shortTitle),['Cadrage','Développement local','Préproduction','Mise en production']);
assert.equal(live.data.decisions.length,0);
assert.equal(live.issues.length,0);
assert.ok(!live.actions[2].includes('start'));
assert.ok(!live.actions[3].includes('start'));
const temporary=await mkdtemp(join(tmpdir(),'protocol-cockpit-fixture-'));
const fixture=JSON.parse(original);
fixture.phases[0].status='awaiting_review';fixture.phases[0].deliveredOn='2026-10-04';fixture.phases[1].status='not_started';fixture.phases[1].startedOn=null;fixture.phases[1].deliveredOn=null;
await writeFile(join(temporary,'suivi-chantier.json'),JSON.stringify(fixture));
for(const file of ['cadrage.md','local.md','preproduction.md','production.md'])await copyFile(join(folder,file),join(temporary,file));
const store=await createReviewStore(temporary);
const view=await store.snapshot();
const result=await store.act({revision:view.revision,phaseId:0,action:'approve',reviewer:'Test fictif uniquement',comment:'Vérifier une copie temporaire, sans décision réelle.',confirm:true,checkedCriteria:fixture.phases[0].exitCriteria.map((_,index)=>index),reviewedArtifacts:view.documents.filter(d=>d.phaseId===0).map(({path,sha256})=>({path,sha256}))});
assert.equal(result.data.phases[0].status,'validated');
assert.equal(result.data.phases[1].status,'not_started');
assert.equal(result.data.publication.deploymentAuthorized,false);
assert.deepEqual(await readFile(join(folder,'suivi-chantier.json')),original);
console.log('Compatibilité des quatre phases et décision fictive : réussies ; suivi réel inchangé.');
